# Brandon had to make a few changes to allow development stage enviroment to work
# I had to uncomment - "target: dev"
# I had to comment - "- ASPNETCORE_ENVIRONMENT=Production" for this to work in development

services:
  blazorapp:

    build: 
      context: .
      # Had to uncomment target dev to do development enviroment. Can comment at production later if needed. - Brandon
      # target: dev
    container_name: team-13-blazor-app
    ports:
      - "5500:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      # I had to comment out the below ASPNETCORE_ENVIROMENT to enable development for application changes
      - ASPNETCORE_ENVIRONMENT=Production # or Development
    volumes:
      - .:/src
      - /src/bin
      - /src/obj
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks: 
      - cse325-team13
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "9e46ec5sFPK0w7uO"
      ACCEPT_EULA: "Y"
    # ports:
    #   - "1433:1433"
    networks:
      - cse325-team13
    volumes:
      - ./Database/seed-data.sql:/docker-entrypoint-initdb.d/seed-data.sql
    restart: unless-stopped
networks:
  cse325-team13:
    driver: bridge









# OLD DOCKER-COMPOSE file

# services:
#   blazorapp:
#     build: .
#     container_name: team-13-blazor-app
#     ports:
#       - "5500:8080"
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=http://0.0.0.0:8080
#       - DOTNET_RUNNING_IN_CONTAINER=true
#       - DOTNET_USE_POLLING_FILE_WATCHER=true
#     restart: "no"
#     develop:
#       watch:
#         - action: rebuild
#           path: .
#           ignore:
#             - bin/
#             - obj/
#             - wwwroot/
    #     - action: sync
    #       path: ./wwwroot
    #       target: /app/wwwroot
    # volumes:
      # - ./wwwroot:/app/wwwroot  # Only mount wwwroot for live CSS updates
    

#run using "docker-compose --build" then access using http://localhost:5500